# SPDX-License-Identifier: LGPL-2.1-or-later
"""Public API probes shared by client compilation and scenario selection.

Probe the configured headers and link library, not a version number: downstream
backports and source-compatible implementations may expose different APIs.
"""

import subprocess
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path

from report_schema import EvidenceRecord


@dataclass(frozen=True)
class LibraryFeature:
    name: str
    declaration: str
    behaviors: tuple[str, ...]

    @property
    def macro(self) -> str:
        return "BLACKBOX_HAVE_" + self.name.upper()


FEATURES = (
    LibraryFeature(
        "flatpak_transaction_progress_get_bytes_per_second",
        "guint64 (*volatile blackbox_probe) (FlatpakTransactionProgress *) = "
        "flatpak_transaction_progress_get_bytes_per_second;",
        ("transaction.rate",),
    ),
)

Executor = Callable[
    [list[str], dict[str, str], Path, list[EvidenceRecord], float],
    subprocess.CompletedProcess[str],
]


def probe_features(cc: str, flags: list[str], env: dict[str, str], output: Path,
                   evidence: list[EvidenceRecord], timeout: float,
                   execute: Executor) -> dict[str, bool]:
    def compile_probe(name: str, body: str) -> subprocess.CompletedProcess[str]:
        source = output / f"probe-{name}.c"
        source.write_text("#include <flatpak.h>\nint main(void) {\n" + body + "\n}\n")
        return execute([cc, "-std=c11", "-Wall", "-Wextra", "-Werror", str(source),
                        "-o", str(output / f"probe-{name}"), *flags],
                       env, output, evidence, timeout)

    baseline = compile_probe("baseline", "return 0;")
    if baseline.returncode:
        raise ValueError(f"library API probe baseline did not compile: {baseline.stderr}")
    available = {}
    for feature in FEATURES:
        # A typed volatile function pointer checks the signature and forces a
        # linker reference even with optimization enabled. Probes are never run.
        result = compile_probe(feature.name,
                               feature.declaration + "\nreturn blackbox_probe == NULL;")
        available[feature.name] = result.returncode == 0
        evidence.append({"observation": "library-api-availability",
                         "data": {"api": feature.name, "available": result.returncode == 0}})
    (output / "blackbox-features.h").write_text(
        "/* Generated by library_features.py for the selected target. */\n"
        + "".join(f"#define {feature.macro} {int(available[feature.name])}\n"
                  for feature in FEATURES)
    )
    return available


def missing_apis(behavior: str, available: dict[str, bool]) -> list[str]:
    return [feature.name for feature in FEATURES
            if behavior in feature.behaviors and not available.get(feature.name, False)]
